### ISSUE TITLE
Tiles not loading when flatgeobuf is generated from ogr2ogr

### ISSUE THREAD

**Issue by overide** [rowanwins/mapbox-gl-flatgeobuf#1]
Hi,

I've converted a `shapefile` to `flatgeobuf` using `ogr2ogr` but when I tried to load it on Mapbox using the same code provided in the example, it doesn't appear on the map.

I can see tiles being requested in the networks tab but tiles don't load on map. I've ensured that `idProperty` is changed accordingly. However, the file provided in the example loads properly.

My flatgeobuf file - https://drive.google.com/file/d/1tWA8zR7ICEo0u-lgpJGoQLw8S57Mr2-p/view?usp=sharing

Thank you

**Comment by rowanwins** [comment]
Hi @overide 

I had a quick look at your flatgeobuf file and the coordinates are stored in EPSG:32643 - WGS 84 / UTM zone 43N. I'm pretty sure you need to convert the coordinates to WGS84.

````
ogr2ogr -t_srs EPSG:4326 output.fgb input.shp
````
Hope that helps

**Comment by overide** [comment]
> Hi @overide
> 
> I had a quick look at your flatgeobuf file and the coordinates are stored in EPSG:32643 - WGS 84 / UTM zone 43N. I'm pretty sure you need to convert the coordinates to WGS84.
> 
> ```
> ogr2ogr -t_srs EPSG:4326 output.fgb input.shp
> ```
> 
> Hope that helps

Thank you so much for the quick response, yes that was the issue.
